name: grpc
services:
  protos:
    container_name: protos
    build: ./protos/
    volumes:
      - ./protos/dist:/app/dist
    restart: on-failure
  proxy:
    container_name: envoy
    build: ./proxy/
    ports:
      - 4000:8080
    environment:
      - SOCKET_ADDRESS=192.168.50.101
      - SOCKET_PORT=50051
    restart: on-failure
    depends_on:
      - protos
      - server  
  server:
    container_name: server
    build: ./server/
    ports:
      - 50051:50051
    volumes:
      - ./protos/dist/js:/app/lib/protos
    restart: on-failure 
    depends_on:
      - protos
  ui:
    container_name: ui
    build:
      context: ./ui/
      args:
        - PROXY_URL=http://192.168.50.101:4000
    ports:
      - 8081:80
    volumes:
      - ./protos/dist/web:/app/lib/protos
    restart: on-failure 
    depends_on:
      - protos
      - server
      - proxy